docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Introduction: intro.md
    - "Theory of Operation": theory.md
    - Reference:
      - "Zend\\Config\\Reader": reader.md
      - "Zend\\Config\\Writer": writer.md
      - "Zend\\Config\\Processor": processor.md
      - "Config Factory": factory.md
      - Migration:
        - "To version 3": migration/to-v3.md
site_name: zend-config
site_description: Zend\Config
repo_url: 'https://github.com/zendframework/zend-config'
copyright: 'Copyright (c) 2005-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
